import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  
  console.log("Public Param", process.env.NEXT_PUBLIC_ALGOD_SERVER);
  console.log("Private Param", process.env.ALGOD_SERVER);
  console.log("Private Param", process.env.ALGOD_SERVER2);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  )
}
export async function getServerSideProps() {
  return {
    props: {}, // will be passed to the page component as props
  }
}
export default Home
